//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MawaqifBackendProxy
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RequestBase", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.TopUpPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.PVTBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.PVTPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.RPBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.RPPaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.TopUpBalanceRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StimulateResponseField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true))
                {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AmountField, value) != true))
                {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineId
        {
            get
            {
                return this.MachineIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MachineIdField, value) != true))
                {
                    this.MachineIdField = value;
                    this.RaisePropertyChanged("MachineId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StimulateResponse
        {
            get
            {
                return this.StimulateResponseField;
            }
            set
            {
                if ((this.StimulateResponseField.Equals(value) != true))
                {
                    this.StimulateResponseField = value;
                    this.RaisePropertyChanged("StimulateResponse");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true))
                {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TopUpPaymentRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class TopUpPaymentRequest : MawaqifBackendProxy.RequestBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTxnIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderInfoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceProviderIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTxnId
        {
            get
            {
                return this.ClientTxnIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ClientTxnIdField, value) != true))
                {
                    this.ClientTxnIdField = value;
                    this.RaisePropertyChanged("ClientTxnId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderInfo
        {
            get
            {
                return this.OrderInfoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OrderInfoField, value) != true))
                {
                    this.OrderInfoField = value;
                    this.RaisePropertyChanged("OrderInfo");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PasswordField, value) != true))
                {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PinField, value) != true))
                {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceId
        {
            get
            {
                return this.ServiceIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ServiceIdField, value) != true))
                {
                    this.ServiceIdField = value;
                    this.RaisePropertyChanged("ServiceId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceProviderId
        {
            get
            {
                return this.ServiceProviderIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ServiceProviderIdField, value) != true))
                {
                    this.ServiceProviderIdField = value;
                    this.RaisePropertyChanged("ServiceProviderId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserNameField, value) != true))
                {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PVTBalanceRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class PVTBalanceRequest : MawaqifBackendProxy.RequestBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeClosedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeClosed
        {
            get
            {
                return this.IncludeClosedField;
            }
            set
            {
                if ((this.IncludeClosedField.Equals(value) != true))
                {
                    this.IncludeClosedField = value;
                    this.RaisePropertyChanged("IncludeClosed");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale
        {
            get
            {
                return this.LocaleField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocaleField, value) != true))
                {
                    this.LocaleField = value;
                    this.RaisePropertyChanged("Locale");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PVTPaymentRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class PVTPaymentRequest : MawaqifBackendProxy.RequestBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KioskLocationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptNoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KioskLocation
        {
            get
            {
                return this.KioskLocationField;
            }
            set
            {
                if ((object.ReferenceEquals(this.KioskLocationField, value) != true))
                {
                    this.KioskLocationField = value;
                    this.RaisePropertyChanged("KioskLocation");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PaymentDateField, value) != true))
                {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptNo
        {
            get
            {
                return this.ReceiptNoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ReceiptNoField, value) != true))
                {
                    this.ReceiptNoField = value;
                    this.RaisePropertyChanged("ReceiptNo");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RPBalanceRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class RPBalanceRequest : MawaqifBackendProxy.RequestBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIdentifierField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocaleId
        {
            get
            {
                return this.LocaleIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocaleIdField, value) != true))
                {
                    this.LocaleIdField = value;
                    this.RaisePropertyChanged("LocaleId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDate
        {
            get
            {
                return this.PaymentDateField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PaymentDateField, value) != true))
                {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentIdentifier
        {
            get
            {
                return this.PaymentIdentifierField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PaymentIdentifierField, value) != true))
                {
                    this.PaymentIdentifierField = value;
                    this.RaisePropertyChanged("PaymentIdentifier");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RPPaymentRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class RPPaymentRequest : MawaqifBackendProxy.RequestBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocaleId
        {
            get
            {
                return this.LocaleIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocaleIdField, value) != true))
                {
                    this.LocaleIdField = value;
                    this.RaisePropertyChanged("LocaleId");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TopUpBalanceRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class TopUpBalanceRequest : MawaqifBackendProxy.RequestBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN
        {
            get
            {
                return this.PINField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PINField, value) != true))
                {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseBase", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.PVTBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.PVTPaymentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.RPBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.RPPaymentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MawaqifBackendProxy.TopUpBalanceResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true))
                {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineId
        {
            get
            {
                return this.MachineIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MachineIdField, value) != true))
                {
                    this.MachineIdField = value;
                    this.RaisePropertyChanged("MachineId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true))
                {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true))
                {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true))
                {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PVTBalanceResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class PVTBalanceResponse : MawaqifBackendProxy.ResponseBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AmountSpecifiedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanbePaidField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IssueDateSpecifiedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlateNumberField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AmountField, value) != true))
                {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.AmountSpecifiedField;
            }
            set
            {
                if ((this.AmountSpecifiedField.Equals(value) != true))
                {
                    this.AmountSpecifiedField = value;
                    this.RaisePropertyChanged("AmountSpecified");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanbePaid
        {
            get
            {
                return this.CanbePaidField;
            }
            set
            {
                if ((this.CanbePaidField.Equals(value) != true))
                {
                    this.CanbePaidField = value;
                    this.RaisePropertyChanged("CanbePaid");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CategoryField, value) != true))
                {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountryField, value) != true))
                {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate
        {
            get
            {
                return this.IssueDateField;
            }
            set
            {
                if ((this.IssueDateField.Equals(value) != true))
                {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IssueDateSpecified
        {
            get
            {
                return this.IssueDateSpecifiedField;
            }
            set
            {
                if ((this.IssueDateSpecifiedField.Equals(value) != true))
                {
                    this.IssueDateSpecifiedField = value;
                    this.RaisePropertyChanged("IssueDateSpecified");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocationField, value) != true))
                {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlateNumber
        {
            get
            {
                return this.PlateNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PlateNumberField, value) != true))
                {
                    this.PlateNumberField = value;
                    this.RaisePropertyChanged("PlateNumber");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stage
        {
            get
            {
                return this.StageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StageField, value) != true))
                {
                    this.StageField = value;
                    this.RaisePropertyChanged("Stage");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TypeField, value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PVTPaymentResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class PVTPaymentResponse : MawaqifBackendProxy.ResponseBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuedDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuedDate
        {
            get
            {
                return this.IssuedDateField;
            }
            set
            {
                if ((this.IssuedDateField.Equals(value) != true))
                {
                    this.IssuedDateField = value;
                    this.RaisePropertyChanged("IssuedDate");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RPBalanceResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class RPBalanceResponse : MawaqifBackendProxy.ResponseBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuedDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PermitCostField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PermitStageField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                if ((this.ExpiryDateField.Equals(value) != true))
                {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuedDate
        {
            get
            {
                return this.IssuedDateField;
            }
            set
            {
                if ((this.IssuedDateField.Equals(value) != true))
                {
                    this.IssuedDateField = value;
                    this.RaisePropertyChanged("IssuedDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PermitCost
        {
            get
            {
                return this.PermitCostField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PermitCostField, value) != true))
                {
                    this.PermitCostField = value;
                    this.RaisePropertyChanged("PermitCost");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PermitStage
        {
            get
            {
                return this.PermitStageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PermitStageField, value) != true))
                {
                    this.PermitStageField = value;
                    this.RaisePropertyChanged("PermitStage");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RPPaymentResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class RPPaymentResponse : MawaqifBackendProxy.ResponseBase
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TopUpBalanceResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class TopUpBalanceResponse : MawaqifBackendProxy.ResponseBase
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalanceAmountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservedAmountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeoutField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BalanceAmount
        {
            get
            {
                return this.BalanceAmountField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BalanceAmountField, value) != true))
                {
                    this.BalanceAmountField = value;
                    this.RaisePropertyChanged("BalanceAmount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservedAmount
        {
            get
            {
                return this.ReservedAmountField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ReservedAmountField, value) != true))
                {
                    this.ReservedAmountField = value;
                    this.RaisePropertyChanged("ReservedAmount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timeout
        {
            get
            {
                return this.TimeoutField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TimeoutField, value) != true))
                {
                    this.TimeoutField = value;
                    this.RaisePropertyChanged("Timeout");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TopUpPaymentResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.MawaqifService.Contracts")]
    [System.SerializableAttribute()]
    public partial class TopUpPaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AmountField, value) != true))
                {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true))
                {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true))
                {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true))
                {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MawaqifBackendProxy.IMBMEMawaqifService")]
    public interface IMBMEMawaqifService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMBMEMawaqifService/TopUpGetBalance", ReplyAction = "http://tempuri.org/IMBMEMawaqifService/TopUpGetBalanceResponse")]
        MawaqifBackendProxy.TopUpBalanceResponse TopUpGetBalance(MawaqifBackendProxy.TopUpBalanceRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMBMEMawaqifService/TopUpPostPayment", ReplyAction = "http://tempuri.org/IMBMEMawaqifService/TopUpPostPaymentResponse")]
        MawaqifBackendProxy.TopUpPaymentResponse TopUpPostPayment(MawaqifBackendProxy.TopUpPaymentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMBMEMawaqifService/PVTGetBalance", ReplyAction = "http://tempuri.org/IMBMEMawaqifService/PVTGetBalanceResponse")]
        MawaqifBackendProxy.PVTBalanceResponse PVTGetBalance(MawaqifBackendProxy.PVTBalanceRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMBMEMawaqifService/PVTPostPayment", ReplyAction = "http://tempuri.org/IMBMEMawaqifService/PVTPostPaymentResponse")]
        MawaqifBackendProxy.PVTPaymentResponse PVTPostPayment(MawaqifBackendProxy.PVTPaymentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMBMEMawaqifService/RPGetBalance", ReplyAction = "http://tempuri.org/IMBMEMawaqifService/RPGetBalanceResponse")]
        MawaqifBackendProxy.RPBalanceResponse RPGetBalance(MawaqifBackendProxy.RPBalanceRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMBMEMawaqifService/RPPostPayment", ReplyAction = "http://tempuri.org/IMBMEMawaqifService/RPPostPaymentResponse")]
        MawaqifBackendProxy.RPPaymentResponse RPPostPayment(MawaqifBackendProxy.RPPaymentRequest request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMBMEMawaqifServiceChannel : MawaqifBackendProxy.IMBMEMawaqifService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MBMEMawaqifServiceClient : System.ServiceModel.ClientBase<MawaqifBackendProxy.IMBMEMawaqifService>, MawaqifBackendProxy.IMBMEMawaqifService
    {

        public MBMEMawaqifServiceClient()
        {
        }

        public MBMEMawaqifServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public MBMEMawaqifServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MBMEMawaqifServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public MBMEMawaqifServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public MawaqifBackendProxy.TopUpBalanceResponse TopUpGetBalance(MawaqifBackendProxy.TopUpBalanceRequest request)
        {
            return base.Channel.TopUpGetBalance(request);
        }

        public MawaqifBackendProxy.TopUpPaymentResponse TopUpPostPayment(MawaqifBackendProxy.TopUpPaymentRequest request)
        {
            return base.Channel.TopUpPostPayment(request);
        }

        public MawaqifBackendProxy.PVTBalanceResponse PVTGetBalance(MawaqifBackendProxy.PVTBalanceRequest request)
        {
            return base.Channel.PVTGetBalance(request);
        }

        public MawaqifBackendProxy.PVTPaymentResponse PVTPostPayment(MawaqifBackendProxy.PVTPaymentRequest request)
        {
            return base.Channel.PVTPostPayment(request);
        }

        public MawaqifBackendProxy.RPBalanceResponse RPGetBalance(MawaqifBackendProxy.RPBalanceRequest request)
        {
            return base.Channel.RPGetBalance(request);
        }

        public MawaqifBackendProxy.RPPaymentResponse RPPostPayment(MawaqifBackendProxy.RPPaymentRequest request)
        {
            return base.Channel.RPPostPayment(request);
        }
    }
}
