//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBMEKiosk.Infrastructure.Proxies.ProxyCardService
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CardRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.CardService.Contracts")]
    [System.SerializableAttribute()]
    public partial class CardRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CardNumberField;

        private string TerminalIdField;

        private string MerchantIdField;

        private string CardResponseCodeField;

        private string AIDField;

        private string AppNameField;

        private string TVRField;

        private string TSIField;

        private string AcInfoField;

        private string AcField;

        private string AuthNumField;

        private string KioskTxnRefNumField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true))
                {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string TerminalId
        {
            get
            {
                return this.TerminalIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TerminalIdField, value) != true))
                {
                    this.TerminalIdField = value;
                    this.RaisePropertyChanged("TerminalId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string MerchantId
        {
            get
            {
                return this.MerchantIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MerchantIdField, value) != true))
                {
                    this.MerchantIdField = value;
                    this.RaisePropertyChanged("MerchantId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public string CardResponseCode
        {
            get
            {
                return this.CardResponseCodeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CardResponseCodeField, value) != true))
                {
                    this.CardResponseCodeField = value;
                    this.RaisePropertyChanged("CardResponseCode");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string AID
        {
            get
            {
                return this.AIDField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AIDField, value) != true))
                {
                    this.AIDField = value;
                    this.RaisePropertyChanged("AID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AppNameField, value) != true))
                {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public string TVR
        {
            get
            {
                return this.TVRField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TVRField, value) != true))
                {
                    this.TVRField = value;
                    this.RaisePropertyChanged("TVR");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public string TSI
        {
            get
            {
                return this.TSIField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TSIField, value) != true))
                {
                    this.TSIField = value;
                    this.RaisePropertyChanged("TSI");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public string AcInfo
        {
            get
            {
                return this.AcInfoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AcInfoField, value) != true))
                {
                    this.AcInfoField = value;
                    this.RaisePropertyChanged("AcInfo");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 9)]
        public string Ac
        {
            get
            {
                return this.AcField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AcField, value) != true))
                {
                    this.AcField = value;
                    this.RaisePropertyChanged("Ac");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 10)]
        public string AuthNum
        {
            get
            {
                return this.AuthNumField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuthNumField, value) != true))
                {
                    this.AuthNumField = value;
                    this.RaisePropertyChanged("AuthNum");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public string KioskTxnRefNum
        {
            get
            {
                return this.KioskTxnRefNumField;
            }
            set
            {
                if ((object.ReferenceEquals(this.KioskTxnRefNumField, value) != true))
                {
                    this.KioskTxnRefNumField = value;
                    this.RaisePropertyChanged("KioskTxnRefNum");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CardFeeRequest", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.CardService.Contracts")]
    [System.SerializableAttribute()]
    public partial class CardFeeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ServiceKeyField;

        private string KioskTxnrefnumField;

        private string KioskTxnRefNum1Field;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ServiceKey
        {
            get
            {
                return this.ServiceKeyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ServiceKeyField, value) != true))
                {
                    this.ServiceKeyField = value;
                    this.RaisePropertyChanged("ServiceKey");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public string KioskTxnrefnum
        {
            get
            {
                return this.KioskTxnrefnumField;
            }
            set
            {
                if ((object.ReferenceEquals(this.KioskTxnrefnumField, value) != true))
                {
                    this.KioskTxnrefnumField = value;
                    this.RaisePropertyChanged("KioskTxnrefnum");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Name = "KioskTxnRefNum", IsRequired = true, Order = 2)]
        public string KioskTxnRefNum1
        {
            get
            {
                return this.KioskTxnRefNum1Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.KioskTxnRefNum1Field, value) != true))
                {
                    this.KioskTxnRefNum1Field = value;//D:\abhijeet\TFS\MBME\KIOSKAPP\source\MBMEKioskCardReader\MBMEKiosk.EtisalateZeepay\etisalatezeepay\pages\receipts\Etisalat-eZeepay_Receipt_card_AR.xaml
                    this.RaisePropertyChanged("KioskTxnRefNum1");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CardFeeResponse", Namespace = "http://schemas.datacontract.org/2004/07/MBMEServices.CardService.Contracts")]
    [System.SerializableAttribute()]
    public partial class CardFeeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FeePercentageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FeePercentage
        {
            get
            {
                return this.FeePercentageField;
            }
            set
            {
                if ((this.FeePercentageField.Equals(value) != true))
                {
                    this.FeePercentageField = value;
                    this.RaisePropertyChanged("FeePercentage");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                if ((this.SuccessField.Equals(value) != true))
                {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MBMEKiosk.Infrastructure.Proxies.ProxyCardService.ICardService")]
    public interface ICardService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICardService/PostCardDetails", ReplyAction = "http://tempuri.org/ICardService/PostCardDetailsResponse")]
        int PostCardDetails(MBMEKiosk.Infrastructure.Proxies.ProxyCardService.CardRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICardService/GetCardFee", ReplyAction = "http://tempuri.org/ICardService/GetCardFeeResponse")]
        MBMEKiosk.Infrastructure.Proxies.ProxyCardService.CardFeeResponse GetCardFee(MBMEKiosk.Infrastructure.Proxies.ProxyCardService.CardFeeRequest request);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardServiceChannel : MBMEKiosk.Infrastructure.Proxies.ProxyCardService.ICardService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardServiceClient : System.ServiceModel.ClientBase<MBMEKiosk.Infrastructure.Proxies.ProxyCardService.ICardService>, MBMEKiosk.Infrastructure.Proxies.ProxyCardService.ICardService
    {

        public CardServiceClient()
        {
        }

        public CardServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CardServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public int PostCardDetails(MBMEKiosk.Infrastructure.Proxies.ProxyCardService.CardRequest request)
        {
            return base.Channel.PostCardDetails(request);
        }

        public MBMEKiosk.Infrastructure.Proxies.ProxyCardService.CardFeeResponse GetCardFee(MBMEKiosk.Infrastructure.Proxies.ProxyCardService.CardFeeRequest request)
        {
            return base.Channel.GetCardFee(request);
        }
    }
}

