//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogMonitoringServiceCleint.MBMELoggerServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestBase", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.PrintCycleLogModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAcceptorStatusRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.CardReaderStatusRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.ReceiptPrinterStatusRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostSessionLogRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAccptanceCycleLog))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.EventLoggerModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.EventLoggerModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.PrintCycleLogModel[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostTransactionRequest[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAccptanceCycleLog[]))]
    public partial class ServiceRequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KioskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KioskId {
            get {
                return this.KioskIdField;
            }
            set {
                if ((object.ReferenceEquals(this.KioskIdField, value) != true)) {
                    this.KioskIdField = value;
                    this.RaisePropertyChanged("KioskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ObjectContext {
            get {
                return this.ObjectContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectContextField, value) != true)) {
                    this.ObjectContextField = value;
                    this.RaisePropertyChanged("ObjectContext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Release {
            get {
                return this.ReleaseField;
            }
            set {
                if ((this.ReleaseField.Equals(value) != true)) {
                    this.ReleaseField = value;
                    this.RaisePropertyChanged("Release");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransId {
            get {
                return this.TransIdField;
            }
            set {
                if ((this.TransIdField.Equals(value) != true)) {
                    this.TransIdField = value;
                    this.RaisePropertyChanged("TransId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintCycleLogModel", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class PrintCycleLogModel : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrnCycleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ReceiptTakenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimePrtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrnCycleId {
            get {
                return this.PrnCycleIdField;
            }
            set {
                if ((this.PrnCycleIdField.Equals(value) != true)) {
                    this.PrnCycleIdField = value;
                    this.RaisePropertyChanged("PrnCycleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ReceiptTaken {
            get {
                return this.ReceiptTakenField;
            }
            set {
                if ((this.ReceiptTakenField.Equals(value) != true)) {
                    this.ReceiptTakenField = value;
                    this.RaisePropertyChanged("ReceiptTaken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimePrt {
            get {
                return this.TimePrtField;
            }
            set {
                if ((this.TimePrtField.Equals(value) != true)) {
                    this.TimePrtField = value;
                    this.RaisePropertyChanged("TimePrt");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashAcceptorStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class CashAcceptorStatusRequest : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] StatusDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] StatusData {
            get {
                return this.StatusDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDataField, value) != true)) {
                    this.StatusDataField = value;
                    this.RaisePropertyChanged("StatusData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardReaderStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class CardReaderStatusRequest : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] StatusDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] StatusData {
            get {
                return this.StatusDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDataField, value) != true)) {
                    this.StatusDataField = value;
                    this.RaisePropertyChanged("StatusData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptPrinterStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class ReceiptPrinterStatusRequest : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] StatusDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] StatusData {
            get {
                return this.StatusDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDataField, value) != true)) {
                    this.StatusDataField = value;
                    this.RaisePropertyChanged("StatusData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class PostTransactionRequest : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TxnTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TransactionAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KioskTransRefNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KioskTxnIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KioskTransDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillerTxnRefNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentModeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TxnTypeId {
            get {
                return this.TxnTypeIdField;
            }
            set {
                if ((this.TxnTypeIdField.Equals(value) != true)) {
                    this.TxnTypeIdField = value;
                    this.RaisePropertyChanged("TxnTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string TransactionDateTime {
            get {
                return this.TransactionDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateTimeField, value) != true)) {
                    this.TransactionDateTimeField = value;
                    this.RaisePropertyChanged("TransactionDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double TransactionAmount {
            get {
                return this.TransactionAmountField;
            }
            set {
                if ((this.TransactionAmountField.Equals(value) != true)) {
                    this.TransactionAmountField = value;
                    this.RaisePropertyChanged("TransactionAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string KioskTransRefNo {
            get {
                return this.KioskTransRefNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KioskTransRefNoField, value) != true)) {
                    this.KioskTransRefNoField = value;
                    this.RaisePropertyChanged("KioskTransRefNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int KioskTxnId {
            get {
                return this.KioskTxnIdField;
            }
            set {
                if ((this.KioskTxnIdField.Equals(value) != true)) {
                    this.KioskTxnIdField = value;
                    this.RaisePropertyChanged("KioskTxnId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string KioskTransDateTime {
            get {
                return this.KioskTransDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.KioskTransDateTimeField, value) != true)) {
                    this.KioskTransDateTimeField = value;
                    this.RaisePropertyChanged("KioskTransDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int BillerID {
            get {
                return this.BillerIDField;
            }
            set {
                if ((this.BillerIDField.Equals(value) != true)) {
                    this.BillerIDField = value;
                    this.RaisePropertyChanged("BillerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string BillerTxnRefNum {
            get {
                return this.BillerTxnRefNumField;
            }
            set {
                if ((object.ReferenceEquals(this.BillerTxnRefNumField, value) != true)) {
                    this.BillerTxnRefNumField = value;
                    this.RaisePropertyChanged("BillerTxnRefNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ConsumerNo {
            get {
                return this.ConsumerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerNoField, value) != true)) {
                    this.ConsumerNoField = value;
                    this.RaisePropertyChanged("ConsumerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int PaymentModeId {
            get {
                return this.PaymentModeIdField;
            }
            set {
                if ((this.PaymentModeIdField.Equals(value) != true)) {
                    this.PaymentModeIdField = value;
                    this.RaisePropertyChanged("PaymentModeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ProductDetail {
            get {
                return this.ProductDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDetailField, value) != true)) {
                    this.ProductDetailField = value;
                    this.RaisePropertyChanged("ProductDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string LastBalance {
            get {
                return this.LastBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.LastBalanceField, value) != true)) {
                    this.LastBalanceField = value;
                    this.RaisePropertyChanged("LastBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NewBalance {
            get {
                return this.NewBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.NewBalanceField, value) != true)) {
                    this.NewBalanceField = value;
                    this.RaisePropertyChanged("NewBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostSessionLogRequest", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class PostSessionLogRequest : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EventCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EventCode {
            get {
                return this.EventCodeField;
            }
            set {
                if ((this.EventCodeField.Equals(value) != true)) {
                    this.EventCodeField = value;
                    this.RaisePropertyChanged("EventCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashAccptanceCycleLog", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class CashAccptanceCycleLog : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EventCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoteValField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeInsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Accepted {
            get {
                return this.AcceptedField;
            }
            set {
                if ((this.AcceptedField.Equals(value) != true)) {
                    this.AcceptedField = value;
                    this.RaisePropertyChanged("Accepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EventCode {
            get {
                return this.EventCodeField;
            }
            set {
                if ((this.EventCodeField.Equals(value) != true)) {
                    this.EventCodeField = value;
                    this.RaisePropertyChanged("EventCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoteId {
            get {
                return this.NoteIdField;
            }
            set {
                if ((this.NoteIdField.Equals(value) != true)) {
                    this.NoteIdField = value;
                    this.RaisePropertyChanged("NoteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoteVal {
            get {
                return this.NoteValField;
            }
            set {
                if ((this.NoteValField.Equals(value) != true)) {
                    this.NoteValField = value;
                    this.RaisePropertyChanged("NoteVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeIns {
            get {
                return this.TimeInsField;
            }
            set {
                if ((this.TimeInsField.Equals(value) != true)) {
                    this.TimeInsField = value;
                    this.RaisePropertyChanged("TimeIns");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLoggerModel", Namespace="http://schemas.datacontract.org/2004/07/KioskSuite.Models.Request")]
    [System.SerializableAttribute()]
    public partial class EventLoggerModel : LogMonitoringServiceCleint.MBMELoggerServiceClient.ServiceRequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventDtTmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventLogIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventDtTm {
            get {
                return this.EventDtTmField;
            }
            set {
                if ((this.EventDtTmField.Equals(value) != true)) {
                    this.EventDtTmField = value;
                    this.RaisePropertyChanged("EventDtTm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventLogId {
            get {
                return this.EventLogIdField;
            }
            set {
                if ((this.EventLogIdField.Equals(value) != true)) {
                    this.EventLogIdField = value;
                    this.RaisePropertyChanged("EventLogId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MBMELoggerServiceClient.IMonitoringService")]
    public interface IMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostEventLog", ReplyAction="http://tempuri.org/IMonitoringService/PostEventLogResponse")]
        short PostEventLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.EventLoggerModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostEventLogCollection", ReplyAction="http://tempuri.org/IMonitoringService/PostEventLogCollectionResponse")]
        short PostEventLogCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.EventLoggerModel[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostPrintCycleLog", ReplyAction="http://tempuri.org/IMonitoringService/PostPrintCycleLogResponse")]
        short PostPrintCycleLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.PrintCycleLogModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostPrintCycleLogCollection", ReplyAction="http://tempuri.org/IMonitoringService/PostPrintCycleLogCollectionResponse")]
        short PostPrintCycleLogCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.PrintCycleLogModel[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/CashAcceptorStatus", ReplyAction="http://tempuri.org/IMonitoringService/CashAcceptorStatusResponse")]
        short CashAcceptorStatus(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAcceptorStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/CardReaderStatus", ReplyAction="http://tempuri.org/IMonitoringService/CardReaderStatusResponse")]
        short CardReaderStatus(LogMonitoringServiceCleint.MBMELoggerServiceClient.CardReaderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/ReceiptPrinterStatus", ReplyAction="http://tempuri.org/IMonitoringService/ReceiptPrinterStatusResponse")]
        short ReceiptPrinterStatus(LogMonitoringServiceCleint.MBMELoggerServiceClient.ReceiptPrinterStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostTransactionLog", ReplyAction="http://tempuri.org/IMonitoringService/PostTransactionLogResponse")]
        short PostTransactionLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostTransactionLogCollection", ReplyAction="http://tempuri.org/IMonitoringService/PostTransactionLogCollectionResponse")]
        short PostTransactionLogCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostTransactionRequest[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostSessionLog", ReplyAction="http://tempuri.org/IMonitoringService/PostSessionLogResponse")]
        short PostSessionLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostSessionLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostCashTxnCycle", ReplyAction="http://tempuri.org/IMonitoringService/PostCashTxnCycleResponse")]
        short PostCashTxnCycle(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAccptanceCycleLog request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/PostCashTxnCycleCollection", ReplyAction="http://tempuri.org/IMonitoringService/PostCashTxnCycleCollectionResponse")]
        short PostCashTxnCycleCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAccptanceCycleLog[] request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/KioskAppStatus", ReplyAction="http://tempuri.org/IMonitoringService/KioskAppStatusResponse")]
        short KioskAppStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringServiceChannel : LogMonitoringServiceCleint.MBMELoggerServiceClient.IMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringServiceClient : System.ServiceModel.ClientBase<LogMonitoringServiceCleint.MBMELoggerServiceClient.IMonitoringService>, LogMonitoringServiceCleint.MBMELoggerServiceClient.IMonitoringService {
        
        public MonitoringServiceClient() {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short PostEventLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.EventLoggerModel request) {
            return base.Channel.PostEventLog(request);
        }
        
        public short PostEventLogCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.EventLoggerModel[] request) {
            return base.Channel.PostEventLogCollection(request);
        }
        
        public short PostPrintCycleLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.PrintCycleLogModel request) {
            return base.Channel.PostPrintCycleLog(request);
        }
        
        public short PostPrintCycleLogCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.PrintCycleLogModel[] request) {
            return base.Channel.PostPrintCycleLogCollection(request);
        }
        
        public short CashAcceptorStatus(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAcceptorStatusRequest request) {
            return base.Channel.CashAcceptorStatus(request);
        }
        
        public short CardReaderStatus(LogMonitoringServiceCleint.MBMELoggerServiceClient.CardReaderStatusRequest request) {
            return base.Channel.CardReaderStatus(request);
        }
        
        public short ReceiptPrinterStatus(LogMonitoringServiceCleint.MBMELoggerServiceClient.ReceiptPrinterStatusRequest request) {
            return base.Channel.ReceiptPrinterStatus(request);
        }
        
        public short PostTransactionLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostTransactionRequest request) {
            return base.Channel.PostTransactionLog(request);
        }
        
        public short PostTransactionLogCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostTransactionRequest[] request) {
            return base.Channel.PostTransactionLogCollection(request);
        }
        
        public short PostSessionLog(LogMonitoringServiceCleint.MBMELoggerServiceClient.PostSessionLogRequest request) {
            return base.Channel.PostSessionLog(request);
        }
        
        public short PostCashTxnCycle(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAccptanceCycleLog request) {
            return base.Channel.PostCashTxnCycle(request);
        }
        
        public short PostCashTxnCycleCollection(LogMonitoringServiceCleint.MBMELoggerServiceClient.CashAccptanceCycleLog[] request) {
            return base.Channel.PostCashTxnCycleCollection(request);
        }
        
        public short KioskAppStatus() {
            return base.Channel.KioskAppStatus();
        }
    }
}
